const CandiateActionTypes = {
  GET_CANDIDATES: "GET_CANDIDATES",
  CLEAR_CANDIDATES: "CLEAR_CANDIDATES",
  SET_DATA: "SET_DATA",
  PROCESS_SHORTLIST: "PROCESS_SHORTLIST",
  PROCESS_REJECT: "PROCESS_REJECT",
};

export default CandiateActionTypes;
